export const dataSource = [
  {
    _id: "620824e8912c141194c1b4a6",
    enabled: true,
    imageUrls: [
      "https://res.cloudinary.com/dhguqxbi6/image/upload/v1643879529/Filter/abstraction/abs_0901-800x800_ob20ny.jpg",
      "https://res.cloudinary.com/dhguqxbi6/image/upload/v1643879529/Filter/abstraction/abs_0902-800x800_ezyylr.jpg",
    ],
    quantity: "1",
    name: "абстракція",
    currentPrice: "1300",
    categories: "abstraction",
    productUrl: "1",
    color: "black",
    size: "60x80",
    itemNo: "610702",
    stars: "4",
    artist: "Anna Smith",
    description:
      "Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.",
    date: "1644700904910",
    __v: "0",
  },
  {
    _id: "620824e9912c141194c1b4a9",
    enabled: true,
    imageUrls: [
      "https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880017/Filter/abstraction/abs_0908-800x800_hfzh5g.jpg",
      "https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880017/Filter/abstraction/abs_0909-800x800_xjjcut.jpg",
    ],
    quantity: "4",
    name: "абстракція",
    currentPrice: "1700",
    categories: "abstraction",
    productUrl: "2",
    color: "red",
    size: "70x100",
    itemNo: "6303",
    stars: "5",
    artist: "Anna",
    description:
      "Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.",
    date: "1644700905025",
    __v: "0",
  },
  {
    _id: "620824e9912c141194c1b4ac",
    enabled: true,
    imageUrls: [
      "https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880186/Filter/abstraction/abst0005-800x800_kmxkiz.jpg",
      "https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880186/Filter/abstraction/abst0006-800x800_iziswe.jpg",
    ],
    quantity: "1",
    name: "абстракція",
    currentPrice: "1780",
    categories: "abstraction",
    productUrl: "3",
    color: "green",
    size: "80x105",
    itemNo: "933328",
    stars: "4",
    artist: "Maria",
    description:
      "Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.",
    date: "1644700905124",
    __v: "0",
  },
];
