module.exports = [{
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643879529/Filter/abstraction/abs_0901-800x800_ob20ny.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643879529/Filter/abstraction/abs_0902-800x800_ezyylr.jpg'],
        quantity: 1,
        name: "Абстракція",
        currentPrice: 1300,
        categories: "abstraction",
        productUrl: "1",
        color: "black",
        size: "60x80",
        itemNo: "1",
        stars: 4,
        artist: 'Anna Smith',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880017/Filter/abstraction/abs_0908-800x800_hfzh5g.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880017/Filter/abstraction/abs_0909-800x800_xjjcut.jpg'],
        quantity: 1,
        name: "Абстракція",
        currentPrice: 1700,
        categories: "abstraction",
        productUrl: "2",
        color: "red",
        size: "70x100",
        itemNo: "2",
        stars: 5,
        artist: 'Anna',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880186/Filter/abstraction/abst0005-800x800_kmxkiz.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880186/Filter/abstraction/abst0006-800x800_iziswe.jpg'],
        quantity: 1,
        name: "Абстракція",
        currentPrice: 1780,
        categories: "abstraction",
        productUrl: "3",
        color: "green",
        size: "80x105",
        itemNo: "3",
        stars: 4,
        artist: 'Maria',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },

    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880441/Filter/abstraction/abst0017-800x800_eycfs6.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880441/Filter/abstraction/abst0018-800x800_zckih8.jpg'],
        quantity: 1,
        name: "Абстракція",
        currentPrice: 1685,
        categories: "abstraction",
        productUrl: "4",
        color: "black",
        size: "90x115",
        itemNo: "4",
        stars: 3,
        artist: 'Alex',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880441/Filter/abstraction/abst0017-800x800_eycfs6.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880441/Filter/abstraction/abst0018-800x800_zckih8.jpg'],
        quantity: 1,
        name: "Абстракція",
        currentPrice: 1885,
        categories: "abstraction",
        productUrl: "5",
        color: "red",
        size: "100x130",
        itemNo: "5",
        stars: 5,
        artist: 'Frank',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880570/Filter/abstraction/abst0019-800x800_g8hcdd.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880570/Filter/abstraction/abst0020-800x800_lbyu5c.jpg'],
        quantity: 1,
        name: "Абстракція",
        currentPrice: 1785,
        categories: "abstraction",
        productUrl: "6",
        color: "green",
        size: "60x80",
        itemNo: "6",
        stars: 3,
        artist: 'Maria',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880749/Filter/abstraction/abst0027-800x800_gvikhx.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880749/Filter/abstraction/abst0026-800x800_rmzh6l.jpg'],
        quantity: 1,
        name: "Абстракція",
        currentPrice: 1311,
        categories: "abstraction",
        productUrl: "7",
        color: "black",
        size: "70x100",
        itemNo: "7",
        stars: 4,
        artist: 'Roman',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880872/Filter/abstraction/abst0042-800x800_x77zuj.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880872/Filter/abstraction/abst0041-800x800_khdxuv.jpg'],
        quantity: 1,
        name: "Абстракція",
        currentPrice: 1784,
        categories: "abstraction",
        productUrl: "8",
        color: "green",
        size: "80x105",
        itemNo: "8",
        stars: 5,
        artist: 'Anna Smith',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880985/Filter/abstraction/abst0046-800x800_t3wepy.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643880985/Filter/abstraction/abst0048-800x800_umixyf.jpg'],
        quantity: 1,
        name: "Абстракція",
        currentPrice: 2084,
        categories: "abstraction",
        productUrl: "9",
        color: "green",
        size: "90x115",
        itemNo: "9",
        stars: 4,
        artist: 'Mark',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643881160/Filter/abstraction/abst0053-800x800_oy1xbn.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643881160/Filter/abstraction/abst0051-800x800_kbjhku.jpg'],
        quantity: 1,
        name: "Абстракція",
        currentPrice: 1376,
        categories: "abstraction",
        productUrl: "10",
        color: "black",
        size: "100x130",
        itemNo: "10",
        stars: 3,
        artist: 'Alex',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643881568/Filter/abstraction/abst0059-800x800_bz5yns.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643881568/Filter/abstraction/abst0058-800x800_grok3j.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643881568/Filter/abstraction/abst0057-800x800_kqyicj.jpg'],
        quantity: 1,
        name: "Абстракція",
        currentPrice: 1325,
        categories: "abstraction",
        productUrl: "11",
        color: "black",
        size: "60x80",
        itemNo: "11",
        stars: 4,
        artist: 'Mark',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643881732/Filter/abstraction/abst0065-800x800_n4pyyl.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643881732/Filter/abstraction/abst0063-800x800_vhooh2.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643881732/Filter/abstraction/abst0064-800x800_wr6gqj.jpg'],
        quantity: 1,
        name: "Абстракція",
        currentPrice: 3000,
        categories: "abstraction",
        productUrl: "12",
        color: "green",
        size: "70x100",
        itemNo: "12",
        stars: 5,
        artist: 'Frank',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885338/Filter/abstraction/intr0001-800x800_uhge8r.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885338/Filter/abstraction/intr0001-800x800_uhge8r.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885338/Filter/abstraction/intr0003-800x800_yki5j3.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1590,
        categories: "interior",
        productUrl: "13",
        color: "black",
        size: "80x105",
        itemNo: "13",
        stars: 4,
        artist: 'Maria',
        description: 'Картини для інтер\'єру написані на натуральному італійському полотні. Ніякого друку або інших технологій.повністю готові і не потребують додаткового доопрацювання. Вони натягнуті на підрамник і покриті захисним шаром акрилового, художнього лаку. Встановлено кріплення та підвіси.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885571/Filter/abstraction/intr0005-800x800_xuzujq.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885571/Filter/abstraction/intr0004-800x800_vim66b.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885571/Filter/abstraction/intr0006-800x800_wjntwx.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1200,
        categories: "interior",
        productUrl: "14",
        color: "green",
        size: "90x115",
        itemNo: "14",
        stars: 3,
        artist: 'Maria',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885683/Filter/abstraction/intr0008-800x800_efxfpu.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885683/Filter/abstraction/intr0009-800x800_hxn8j6.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885683/Filter/abstraction/intr0007-800x800_fmhhtu.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 2100,
        categories: "interior",
        productUrl: "15",
        color: "red",
        size: "100x130",
        itemNo: "15",
        stars: 5,
        artist: 'Mark',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885852/Filter/abstraction/intr0018-800x800_jupyna.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885852/Filter/abstraction/intr0016-800x800_lqvl87.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1100,
        categories: "interior",
        productUrl: "16",
        color: "black",
        size: "60x80",
        itemNo: "16",
        stars: 4,
        artist: 'Alex',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885974/Filter/abstraction/intr0025-800x800_vzi1e1.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885974/Filter/abstraction/intr0026-800x800_gou3fa.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643885974/Filter/abstraction/intr0027-800x800_ukjsze.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1500,
        categories: "interior",
        productUrl: "17",
        color: "green",
        size: "70x100",
        itemNo: "17",
        stars: 4,
        artist: 'Mark',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643886159/Filter/abstraction/intr0030-800x800_krhivq.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643886159/Filter/abstraction/intr0029-800x800_gkd4cy.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643886159/Filter/abstraction/intr0028-800x800_vipfu3.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1220,
        categories: "interior",
        productUrl: "18",
        color: "green",
        size: "80x105",
        itemNo: "18",
        stars: 4,
        artist: 'Frank',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643886355/Filter/abstraction/intr0035-800x800_f70zhe.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643886355/Filter/abstraction/intr0034-800x800_kyzlam.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1130,
        categories: "interior",
        productUrl: "19",
        color: "black",
        size: "90x115",
        itemNo: "19",
        stars: 4,
        artist: 'Frank',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643886503/Filter/abstraction/intr0037-800x800_jaf3jk.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643886503/Filter/abstraction/intr0036-800x800_yevbrp.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1340,
        categories: "interior",
        productUrl: "20",
        color: "green",
        size: "100x130",
        itemNo: "20",
        stars: 5,
        artist: '',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643886624/Filter/abstraction/intr0032-800x800_bamipl.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643886624/Filter/abstraction/intr0033-800x800_uuhgyk.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643886624/Filter/abstraction/intr0031-800x800_mftsot.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1800,
        categories: "interior",
        productUrl: "21",
        color: "green",
        size: "60x80",
        itemNo: "21",
        stars: 4,
        artist: 'Maria',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643886812/Filter/abstraction/itr_0007-800x800_zitoxw.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1270,
        categories: "interior",
        productUrl: "22",
        color: "red",
        size: "70x100",
        itemNo: "22",
        stars: 4,
        artist: 'Roman',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643886917/Filter/abstraction/itr_0058-800x800_eyrmpz.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643886916/Filter/abstraction/itr_0057-800x800_terupr.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1300,
        categories: "interior",
        productUrl: "23",
        color: "black",
        size: "80x105",
        itemNo: "23",
        stars: 4,
        artist: 'Frank',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643887019/Filter/abstraction/itr_0061-800x800_zqj7rz.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643887019/Filter/abstraction/itr_0062-800x800_islkpm.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1290,
        categories: "interior",
        productUrl: "24",
        color: "green",
        size: "90x115",
        itemNo: "24",
        stars: 4,
        artist: 'Mark',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643887128/Filter/abstraction/itr_0074-800x800_u2d4rn.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643887128/Filter/abstraction/itr_0075-800x800_ozugzd.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643887128/Filter/abstraction/itr_0073-800x800_pk49aw.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 2245,
        categories: "interior",
        productUrl: "25",
        color: "black",
        size: "100x130",
        itemNo: "25",
        stars: 4,
        artist: 'Mark',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643887280/Filter/abstraction/itr_0084-800x800_xkerrv.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1498,
        categories: "interior",
        productUrl: "26",
        color: "green",
        size: "60x80",
        itemNo: "26",
        stars: 4,
        artist: 'Anna',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643887450/Filter/abstraction/itr_0266-800x800_ujpy9t.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643887450/Filter/abstraction/itr_0267-800x800_nelse1.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1276,
        categories: "interior",
        productUrl: "27",
        color: "green",
        size: "70x100",
        itemNo: "27",
        stars: 4,
        artist: 'Mark',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643887607/Filter/abstraction/itr_0189-800x800_tqrqnk.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643887607/Filter/abstraction/itr_0188-800x800_drutih.jpg'],
        quantity: 1,
        name: "Інтер'єрна картина",
        currentPrice: 1200,
        categories: "interior",
        productUrl: "28",
        color: "red",
        size: "80x105",
        itemNo: "28",
        stars: 4,
        artist: 'Maria',
        description: 'Картина абстракція на полотні. Ручна робота художника. Ніякого друку або інших технологій. Тільки станковий живопис від художників. Картина виконана з використанням художнього акрилу, масляних фарб, структурних гелів та паст. Кистями та мастихіном. Абстракція повністю закінчена, натягнута на підрамник, покрита подвійним шаром акрилового, художнього лаку.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643887911/Filter/abstraction/ntlm_0006-800x800_fqgy6z.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643887911/Filter/abstraction/ntlm_0005-800x800_bx1l9r.jpg'],
        quantity: 1,
        name: "Модульна картина для інтер'єру",
        currentPrice: 1250,
        categories: "oilModule",
        productUrl: "29",
        color: "red",
        size: "90x115",
        itemNo: "29",
        stars: 4,
        artist: 'Frank',
        description: 'Модульні картини для інтер\'єру – картини з декількох частин на полотні. Модульні картини для інтер\'єру написані професійними художниками олійними фарбами, а також художнім акрилом. Залежно від техніки виконання художники стилізують твір: структурними пастами, об\'ємними гелями та акриловими контурами.\n' +
            'Модульні картини для інтер\'єру малюються на високоякісному, натуральному італійському полотні. Картини вкриті подвійним, захисним шаром художнього лаку, який зберігає живопис від вигоряння під променями сонця, а також механічних впливів.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643888049/Filter/abstraction/ntlm_0009-800x800_fbeul8.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643888049/Filter/abstraction/ntlm_0008-800x800_io1hne.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643888049/Filter/abstraction/ntlm_0007-800x800_rxpzyu.jpg'],
        quantity: 1,
        name: "Модульна картина для інтер'єру",
        currentPrice: 1150,
        categories: "oilModule",
        productUrl: "30",
        color: "green",
        size: "100x130",
        itemNo: "30",
        stars: 4,
        artist: 'Alex',
        description: 'Модульні картини для інтер\'єру – картини з декількох частин на полотні. Модульні картини для інтер\'єру написані професійними художниками олійними фарбами, а також художнім акрилом. Залежно від техніки виконання художники стилізують твір: структурними пастами, об\'ємними гелями та акриловими контурами.\n' +
            'Модульні картини для інтер\'єру малюються на високоякісному, натуральному італійському полотні. Картини вкриті подвійним, захисним шаром художнього лаку, який зберігає живопис від вигоряння під променями сонця, а також механічних впливів.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643888409/Filter/abstraction/absm_0057-800x800_elwete.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643888410/Filter/abstraction/absm_0056-800x800_n7sd9q.jpg'],
        quantity: 1,
        name: "Модульна картина для інтер'єру",
        currentPrice: 1136,
        categories: "oilModule",
        productUrl: "31",
        color: "green",
        size: "60x80",
        itemNo: "31",
        stars: 4,
        artist: 'Anna Smith',
        description: 'Модульні картини для інтер\'єру – картини з декількох частин на полотні. Модульні картини для інтер\'єру написані професійними художниками олійними фарбами, а також художнім акрилом. Залежно від техніки виконання художники стилізують твір: структурними пастами, об\'ємними гелями та акриловими контурами.\n' +
            'Модульні картини для інтер\'єру малюються на високоякісному, натуральному італійському полотні. Картини вкриті подвійним, захисним шаром художнього лаку, який зберігає живопис від вигоряння під променями сонця, а також механічних впливів.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643888633/Filter/abstraction/absm_0061-800x800_uqekd5.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643888633/Filter/abstraction/absm_0060-800x800_saugrj.jpg'],
        quantity: 1,
        name: "Модульна картина для інтер'єру",
        currentPrice: 3100,
        categories: "oilModule",
        productUrl: "32",
        color: "black",
        size: "70x100",
        itemNo: "32",
        stars: 4,
        artist: 'Frank',
        description: 'Модульні картини для інтер\'єру – картини з декількох частин на полотні. Модульні картини для інтер\'єру написані професійними художниками олійними фарбами, а також художнім акрилом. Залежно від техніки виконання художники стилізують твір: структурними пастами, об\'ємними гелями та акриловими контурами.\n' +
            'Модульні картини для інтер\'єру малюються на високоякісному, натуральному італійському полотні. Картини вкриті подвійним, захисним шаром художнього лаку, який зберігає живопис від вигоряння під променями сонця, а також механічних впливів.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643888775/Filter/abstraction/fosm_0007-800x800_njezaa.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643888775/Filter/abstraction/fosm_0009-800x800_sgdw6c.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643888775/Filter/abstraction/fosm_0008-800x800_fgkdak.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643888775/Filter/abstraction/fosm_0006-800x800_lywba8.jpg'],
        quantity: 1,
        name: "Модульна картина для інтер'єру",
        currentPrice: 1500,
        categories: "oilModule",
        productUrl: "33",
        color: "black",
        size: "80x105",
        itemNo: "33",
        stars: 4,
        artist: 'Anna',
        description: 'Модульні картини для інтер\'єру – картини з декількох частин на полотні. Модульні картини для інтер\'єру написані професійними художниками олійними фарбами, а також художнім акрилом. Залежно від техніки виконання художники стилізують твір: структурними пастами, об\'ємними гелями та акриловими контурами.\n' +
            'Модульні картини для інтер\'єру малюються на високоякісному, натуральному італійському полотні. Картини вкриті подвійним, захисним шаром художнього лаку, який зберігає живопис від вигоряння під променями сонця, а також механічних впливів.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643893486/Filter/abstraction/fosm_0024-800x800_jwqswi.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643893486/Filter/abstraction/fosm_0023-800x800_cqpnu7.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643893486/Filter/abstraction/fosm_0022-800x800_eye1rq.jpg'],
        quantity: 1,
        name: "Модульна картина для інтер'єру",
        currentPrice: 1720,
        categories: "oilModule",
        productUrl: "34",
        color: "red",
        size: "90x115",
        itemNo: "34",
        stars: 4,
        artist: 'Roman',
        description: 'Модульні картини для інтер\'єру – картини з декількох частин на полотні. Модульні картини для інтер\'єру написані професійними художниками олійними фарбами, а також художнім акрилом. Залежно від техніки виконання художники стилізують твір: структурними пастами, об\'ємними гелями та акриловими контурами.\n' +
            'Модульні картини для інтер\'єру малюються на високоякісному, натуральному італійському полотні. Картини вкриті подвійним, захисним шаром художнього лаку, який зберігає живопис від вигоряння під променями сонця, а також механічних впливів.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643893670/Filter/abstraction/fosm_0092-800x800_fri5is.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643893670/Filter/abstraction/fosm_0091-800x800_tawymm.jpg'],
        quantity: 1,
        name: "Модульна картина для інтер'єру",
        currentPrice: 1100,
        categories: "oilModule",
        productUrl: "35",
        color: "green",
        size: "100x130",
        itemNo: "35",
        stars: 4,
        artist: 'Alex',
        description: 'Модульні картини для інтер\'єру – картини з декількох частин на полотні. Модульні картини для інтер\'єру написані професійними художниками олійними фарбами, а також художнім акрилом. Залежно від техніки виконання художники стилізують твір: структурними пастами, об\'ємними гелями та акриловими контурами.\n' +
            'Модульні картини для інтер\'єру малюються на високоякісному, натуральному італійському полотні. Картини вкриті подвійним, захисним шаром художнього лаку, який зберігає живопис від вигоряння під променями сонця, а також механічних впливів.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643894972/Filter/abstraction/sity0032-800x800_wqolmr.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643894972/Filter/abstraction/sity0031-800x800_mqnqr3.jpg'],
        quantity: 1,
        name: "Міський пейзаж",
        currentPrice: 1290,
        categories: "cityscape",
        productUrl: "36",
        color: "red",
        size: "60x80",
        itemNo: "36",
        stars: 4,
        artist: 'Maria',
        description: 'Картини на полотні ручної роботи художників. Картина міський пейзаж написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643895330/Filter/abstraction/syt_0123-800x800_i6ayhg.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643895330/Filter/abstraction/syt_0122-800x800_wg87vk.jpg'],
        quantity: 1,
        name: "Міський пейзаж",
        currentPrice: 1520,
        categories: "cityscape",
        productUrl: "37",
        color: "green",
        size: "70x100",
        itemNo: "37",
        stars: 4,
        artist: 'Roman',
        description: 'Картини на полотні ручної роботи художників. Картина міський пейзаж написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643895532/Filter/abstraction/syt_0097-800x800_eyymge.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643895532/Filter/abstraction/syt_0096-800x800_g8x64d.jpg'],
        quantity: 1,
        name: "Міський пейзаж",
        currentPrice: 1040,
        categories: "cityscape",
        productUrl: "38",
        color: "black",
        size: "80x105",
        itemNo: "38",
        stars: 4,
        artist: 'Mark',
        description: 'Картини на полотні ручної роботи художників. Картина міський пейзаж написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643896465/Filter/abstraction/syt_0117-800x800_mntg6x.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643896465/Filter/abstraction/syt_0119-800x800_gezmgz.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643896465/Filter/abstraction/syt_0118-800x800_y7fq6w.jpg'],
        quantity: 1,
        name: "Міський пейзаж",
        currentPrice: 3100,
        categories: "cityscape",
        productUrl: "39",
        color: "red",
        size: "90x115",
        itemNo: "39",
        stars: 4,
        artist: 'Mark',
        description: 'Картини на полотні ручної роботи художників. Картина міський пейзаж написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643897206/Filter/abstraction/syt_0044-800x800_jebsml.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643897206/Filter/abstraction/syt_0042-800x800_aaa1ao.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643897206/Filter/abstraction/syt_0043-800x800_gw0yds.jpg'],
        quantity: 1,
        name: "Міський пейзаж",
        currentPrice: 1400,
        categories: "cityscape",
        productUrl: "40",
        color: "red",
        size: "100x130",
        itemNo: "40",
        stars: 4,
        artist: 'Frank',
        description: 'Картини на полотні ручної роботи художників. Картина міський пейзаж написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643897456/Filter/abstraction/syt_0050-800x800_o4zara.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643897456/Filter/abstraction/syt_0049-800x800_fztywa.jpg'],
        quantity: 1,
        name: "Міський пейзаж",
        currentPrice: 2004,
        categories: "cityscape",
        productUrl: "41",
        color: "red",
        size: "60x80",
        itemNo: "41",
        stars: 4,
        artist: 'Frank',
        description: 'Картини на полотні ручної роботи художників. Картина міський пейзаж написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643897632/Filter/abstraction/syt_0045-800x800_cef7mn.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643897631/Filter/abstraction/syt_0047-800x800_a9oafz.jpg'],
        quantity: 1,
        name: "Міський пейзаж",
        currentPrice: 1600,
        categories: "cityscape",
        productUrl: "42",
        color: "black",
        size: "70x100",
        itemNo: "42",
        stars: 4,
        artist: 'Anna',
        description: 'Картини на полотні ручної роботи художників. Картина міський пейзаж написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643897805/Filter/abstraction/syt_0062-800x800_iatfep.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643897805/Filter/abstraction/syt_0061-800x800_wq7upm.jpg'],
        quantity: 1,
        name: "Міський пейзаж",
        currentPrice: 1150,
        categories: "cityscape",
        productUrl: "43",
        color: "green",
        size: "80x105",
        itemNo: "43",
        stars: 4,
        artist: 'Anna Smith',
        description: 'Картини на полотні ручної роботи художників. Картина міський пейзаж написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643897999/Filter/abstraction/syt_0065-800x800_bxgk4y.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643897999/Filter/abstraction/syt_0063-800x800_y67fbi.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643897999/Filter/abstraction/syt_0066-800x800_n8br94.jpg'],
        quantity: 1,
        name: "Міський пейзаж",
        currentPrice: 1130,
        categories: "cityscape",
        productUrl: "44",
        color: "green",
        size: "90x115",
        itemNo: "44",
        stars: 4,
        artist: 'Anna',
        description: 'Картини на полотні ручної роботи художників. Картина міський пейзаж написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643898335/Filter/abstraction/syt_0071-800x800_huu3cb.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643898335/Filter/abstraction/syt_0072-800x800_zgpnb8.jpg'],
        quantity: 1,
        name: "Міський пейзаж",
        currentPrice: 1422,
        categories: "cityscape",
        productUrl: "45",
        color: "black",
        size: "100x130",
        itemNo: "45",
        stars: 4,
        artist: 'Frank',
        description: 'Картини на полотні ручної роботи художників. Картина міський пейзаж написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643898607/Filter/abstraction/syt_0013-800x800_wcrtdf.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643898607/Filter/abstraction/syt_0014-800x800_ihn2i4.jpg'],
        quantity: 1,
        name: "Міський пейзаж",
        currentPrice: 1700,
        categories: "cityscape",
        productUrl: "46",
        color: "black",
        size: "60x80",
        itemNo: "46",
        stars: 4,
        artist: 'Maria',
        description: 'Картини на полотні ручної роботи художників. Картина міський пейзаж написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643899066/Filter/abstraction/anml0006-800x800_futgri.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643899066/Filter/abstraction/anml0007-800x800_z1kqff.jpg'],
        quantity: 1,
        name: "Картини тварин",
        currentPrice: 2160,
        categories: "animals",
        productUrl: "47",
        color: "red",
        size: "70x100",
        itemNo: "47",
        stars: 4,
        artist: 'Roman',
        description: 'Картини на полотні ручної роботи художників. Картина написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643899294/Filter/abstraction/anml0001-800x800_ta5gpl.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643899294/Filter/abstraction/anml0002-800x800_kctwip.jpg'],
        quantity: 1,
        name: "Картини тварин",
        currentPrice: 1780,
        categories: "animals",
        productUrl: "48",
        color: "red",
        size: "80x105",
        itemNo: "48",
        stars: 4,
        artist: 'Alex',
        description: 'Картини на полотні ручної роботи художників. Картина написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643899421/Filter/abstraction/anml0015-800x800_oqotua.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643899421/Filter/abstraction/anml0014-800x800_wt3hcs.jpg'],
        quantity: 1,
        name: "Картини тварин",
        currentPrice: 2300,
        categories: "animals",
        productUrl: "49",
        color: "green",
        size: "90x115",
        itemNo: "49",
        stars: 4,
        artist: 'Anna Smith',
        description: 'Картини на полотні ручної роботи художників. Картина написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643901213/Filter/abstraction/jvo_0101-800x800_tymvii.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643901213/Filter/abstraction/jvo_0102-800x800_sz75ty.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643901213/Filter/abstraction/jvo_0100-800x800_rwzn0m.jpg'],
        quantity: 1,
        name: "Картини тварин",
        currentPrice: 2100,
        categories: "animals",
        productUrl: "50",
        color: "red",
        size: "100x130",
        itemNo: "50",
        stars: 4,
        artist: 'Anna',
        description: 'Картини на полотні ручної роботи художників. Картина написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643901504/Filter/abstraction/jvo_0108-800x800_pc5xdr.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643901504/Filter/abstraction/jvo_0107-800x800_zntz8j.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643901504/Filter/abstraction/jvo_0106-800x800_vb6odw.jpg'],
        quantity: 1,
        name: "Картини тварин",
        currentPrice: 2300,
        categories: "animals",
        productUrl: "51",
        color: "green",
        size: "60x80",
        itemNo: "51",
        stars: 4,
        artist: 'Frank',
        description: 'Картини на полотні ручної роботи художників. Картина написана художнім акрилом, олійними фарбами із застосуванням структурних гелів, медіумів та паст. Картина на полотні міський краєвид повністю закінчений. Вона покрита захисним шаром лаку, натягнута на підрамник, встановлені підвіси для кріплення на стіні.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643901914/Filter/abstraction/more0011-800x800_eiyj8t.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643901914/Filter/abstraction/more0012-800x800_mok6l8.jpg'],
        quantity: 1,
        name: "Картина морський пейзаж",
        currentPrice: 1300,
        categories: "seascape",
        productUrl: "52",
        color: "red",
        size: "70x100",
        itemNo: "52",
        stars: 4,
        artist: 'Anna',
        description: 'Картина моря «Морський пейзаж» повністю закінчена, вона покрита захисним шаром художнього лаку, натягнута на підрамник, та встановлені кріплення. Картина море виконана на італійському полотні з галерейною натяжкою за підрамник, що дозволяє вішати картину морський пейзаж без багетної рами.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643901914/Filter/abstraction/more0011-800x800_eiyj8t.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643901914/Filter/abstraction/more0012-800x800_mok6l8.jpg'],
        quantity: 1,
        name: "Картина морський пейзаж",
        currentPrice: 1900,
        categories: "seascape",
        productUrl: "53",
        color: "green",
        size: "80x105",
        itemNo: "53",
        stars: 4,
        artist: 'Roman',
        description: 'Картина моря «Морський пейзаж» повністю закінчена, вона покрита захисним шаром художнього лаку, натягнута на підрамник, та встановлені кріплення. Картина море виконана на італійському полотні з галерейною натяжкою за підрамник, що дозволяє вішати картину морський пейзаж без багетної рами.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643902293/Filter/abstraction/more0032-800x800_ndxsy8.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643902293/Filter/abstraction/more0034-800x800_mj2zvy.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643902293/Filter/abstraction/more0033-800x800_dmskio.jpg'],
        quantity: 1,
        name: "Картина морський пейзаж",
        currentPrice: 1200,
        categories: "seascape",
        productUrl: "54",
        color: "black",
        size: "90x115",
        itemNo: "54",
        stars: 4,
        artist: 'Frank',
        description: 'Картина моря «Морський пейзаж» повністю закінчена, вона покрита захисним шаром художнього лаку, натягнута на підрамник, та встановлені кріплення. Картина море виконана на італійському полотні з галерейною натяжкою за підрамник, що дозволяє вішати картину морський пейзаж без багетної рами.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643902887/Filter/abstraction/more0022-600x600_lgf3ce.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643902962/Filter/abstraction/more0020-800x800_i0tjcj.jpg'],
        quantity: 1,
        name: "Картина морський пейзаж",
        currentPrice: 1300,
        categories: "seascape",
        productUrl: "55",
        color: "green",
        size: "100x130",
        itemNo: "55",
        stars: 4,
        artist: 'Roman',
        description: 'Картина моря «Морський пейзаж» повністю закінчена, вона покрита захисним шаром художнього лаку, натягнута на підрамник, та встановлені кріплення. Картина море виконана на італійському полотні з галерейною натяжкою за підрамник, що дозволяє вішати картину морський пейзаж без багетної рами.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643903563/Filter/abstraction/more0048-800x800_uj8ciq.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643903563/Filter/abstraction/more0049-800x800_nc6wji.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643903563/Filter/abstraction/more0050-800x800_z0w8fg.jpg'],
        quantity: 1,
        name: "Картина морський пейзаж",
        currentPrice: 1400,
        categories: "seascape",
        productUrl: "56",
        color: "green",
        size: "60x80",
        itemNo: "56",
        stars: 4,
        artist: 'Roman',
        description: 'Картина моря «Морський пейзаж» повністю закінчена, вона покрита захисним шаром художнього лаку, натягнута на підрамник, та встановлені кріплення. Картина море виконана на італійському полотні з галерейною натяжкою за підрамник, що дозволяє вішати картину морський пейзаж без багетної рами.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643903930/Filter/abstraction/more0026-800x800_zeooie.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643903930/Filter/abstraction/more0028-800x800_qqlbln.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643903930/Filter/abstraction/more0027-800x800_uz9jsl.jpg'],
        quantity: 1,
        name: "Картина морський пейзаж",
        currentPrice: 1160,
        categories: "seascape",
        productUrl: "57",
        color: "red",
        size: "70x100",
        itemNo: "57",
        stars: 4,
        artist: 'Maria',
        description: 'Картина моря «Морський пейзаж» повністю закінчена, вона покрита захисним шаром художнього лаку, натягнута на підрамник, та встановлені кріплення. Картина море виконана на італійському полотні з галерейною натяжкою за підрамник, що дозволяє вішати картину морський пейзаж без багетної рами.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643904547/Filter/abstraction/ntl_0054-800x800_ycrfge.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643904547/Filter/abstraction/ntl_0053-800x800_t0rhi2.jpg'],
        quantity: 1,
        name: "Краєвиди природи",
        currentPrice: 1510,
        categories: "nature",
        productUrl: "58",
        color: "black",
        size: "80x105",
        itemNo: "58",
        stars: 4,
        artist: 'Roman',
        description: 'Картина олією краєвиди природи ручної роботи художника. Картина виконана професійним живописцем акриловими та олійними фарбами, із застосуванням структурних гелів, паст, медіумів та контурів. Основа картини – якісне італійське полотно на дерев\'яному підрамнику. Скоби заховані за торець, тому картину краєвид можна вішати без рами.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643904700/Filter/abstraction/ntl_0022-800x800_samm4c.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643904700/Filter/abstraction/ntl_0021-800x800_r57vhm.jpg'],
        quantity: 1,
        name: "Краєвиди природи",
        currentPrice: 2160,
        categories: "nature",
        productUrl: "59",
        color: "black",
        size: "90x115",
        itemNo: "59",
        stars: 4,
        artist: 'Roman',
        description: 'Картина олією краєвиди природи ручної роботи художника. Картина виконана професійним живописцем акриловими та олійними фарбами, із застосуванням структурних гелів, паст, медіумів та контурів. Основа картини – якісне італійське полотно на дерев\'яному підрамнику. Скоби заховані за торець, тому картину краєвид можна вішати без рами.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643904965/Filter/abstraction/ntl_0006-800x800_gpjfop.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643904965/Filter/abstraction/ntl_0008-800x800_yzprvt.jpg'],
        quantity: 1,
        name: "Краєвиди природи",
        currentPrice: 2160,
        categories: "nature",
        productUrl: "60",
        color: "red",
        size: "100x130",
        itemNo: "60",
        stars: 4,
        artist: 'Anna',
        description: 'Картина олією краєвиди природи ручної роботи художника. Картина виконана професійним живописцем акриловими та олійними фарбами, із застосуванням структурних гелів, паст, медіумів та контурів. Основа картини – якісне італійське полотно на дерев\'яному підрамнику. Скоби заховані за торець, тому картину краєвид можна вішати без рами.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643905137/Filter/abstraction/ntl_0002-800x800_uo0rww.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643905137/Filter/abstraction/ntl_0001-800x800_ibolc5.jpg'],
        quantity: 1,
        name: "Краєвиди природи",
        currentPrice: 1900,
        categories: "nature",
        productUrl: "61",
        color: "red",
        size: "60x80",
        itemNo: "61",
        stars: 4,
        artist: 'Mark',
        description: 'Картина олією краєвиди природи ручної роботи художника. Картина виконана професійним живописцем акриловими та олійними фарбами, із застосуванням структурних гелів, паст, медіумів та контурів. Основа картини – якісне італійське полотно на дерев\'яному підрамнику. Скоби заховані за торець, тому картину краєвид можна вішати без рами.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643905673/Filter/abstraction/flwr0010-800x800_hjbodh.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643905673/Filter/abstraction/flwr0009-800x800_xhkjoe.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643905674/Filter/abstraction/flwr0008-800x800_xcyrwh.jpg'],
        quantity: 1,
        name: "Картина квіти",
        currentPrice: 1800,
        categories: "oilFlowers",
        productUrl: "62",
        color: "black",
        size: "70x100",
        itemNo: "62",
        stars: 4,
        artist: 'Mark',
        description: 'Картина квіти олією – ручна робота художника. Картина написана на італійському полотні, олією та художнім акрилом. Художник також використовував структурні гелі та пасти, медіуми та акрилові контури. Картина квіти маслом закріплена подвійним шаром акрилового лаку, який захищає від вигоряння та механічних пошкоджень.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643905852/Filter/abstraction/flwr0058-800x800_fygkr5.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643905852/Filter/abstraction/flwr0059-800x800_lcbekc.jpg'],
        quantity: 1,
        name: "Картина квіти",
        currentPrice: 1270,
        categories: "oilFlowers",
        productUrl: "63",
        color: "green",
        size: "80x105",
        itemNo: "63",
        stars: 4,
        artist: 'Alex',
        description: 'Картина квіти олією – ручна робота художника. Картина написана на італійському полотні, олією та художнім акрилом. Художник також використовував структурні гелі та пасти, медіуми та акрилові контури. Картина квіти маслом закріплена подвійним шаром акрилового лаку, який захищає від вигоряння та механічних пошкоджень.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643906087/Filter/abstraction/flwr0091-800x800_fb5tdg.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643906086/Filter/abstraction/flwr0092-800x800_bi5u1t.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643906086/Filter/abstraction/flwr0090-800x800_lfhlxm.jpg'],
        quantity: 1,
        name: "Картина квіти",
        currentPrice: 1020,
        categories: "oilFlowers",
        productUrl: "64",
        color: "green",
        size: "90x115",
        itemNo: "64",
        stars: 4,
        artist: 'Maria',
        description: 'Картина квіти олією – ручна робота художника. Картина написана на італійському полотні, олією та художнім акрилом. Художник також використовував структурні гелі та пасти, медіуми та акрилові контури. Картина квіти маслом закріплена подвійним шаром акрилового лаку, який захищає від вигоряння та механічних пошкоджень.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643906238/Filter/abstraction/flwr0097-800x800_sbmor1.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643906238/Filter/abstraction/flwr0096-800x800_g3ajht.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643906239/Filter/abstraction/flwr0098-800x800_gre42e.jpg'],
        quantity: 1,
        name: "Картина квіти",
        currentPrice: 2000,
        categories: "oilFlowers",
        productUrl: "65",
        color: "red",
        size: "100x130",
        itemNo: "65",
        stars: 4,
        artist: 'Anna Smith',
        description: 'Картина квіти олією – ручна робота художника. Картина написана на італійському полотні, олією та художнім акрилом. Художник також використовував структурні гелі та пасти, медіуми та акрилові контури. Картина квіти маслом закріплена подвійним шаром акрилового лаку, який захищає від вигоряння та механічних пошкоджень.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643906460/Filter/abstraction/fos_0040-800x800_gypw23.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643906460/Filter/abstraction/fos_0039-800x800_axaeou.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643906460/Filter/abstraction/fos_0038-800x800_gqqkcm.jpg'],
        quantity: 1,
        name: "Картина квіти",
        currentPrice: 1101,
        categories: "oilFlowers",
        productUrl: "66",
        color: "green",
        size: "60x80",
        itemNo: "66",
        stars: 4,
        artist: 'Alex',
        description: 'Картина квіти олією – ручна робота художника. Картина написана на італійському полотні, олією та художнім акрилом. Художник також використовував структурні гелі та пасти, медіуми та акрилові контури. Картина квіти маслом закріплена подвійним шаром акрилового лаку, який захищає від вигоряння та механічних пошкоджень.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643908384/Filter/abstraction/itrm_0003-800x800_ygxgmt.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643908384/Filter/abstraction/itrm_0002-800x800_m8u9sl.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643908384/Filter/abstraction/itrm_0001-800x800_ku8ued.jpg'],
        quantity: 1,
        name: "Модульні картини природи",
        currentPrice: 1101,
        categories: "modules",
        productUrl: "67",
        color: "red",
        size: "70x100",
        itemNo: "67",
        stars: 4,
        artist: 'Anna Smith',
        description: 'Модульні картини природи, написані маслом або художнім акрилом, професійними художниками вручну, з використанням декоративних матеріалів: структурних гелів та паст, акрилових контурів та медіумів. Усі модульні картини природи пишуться на натуральному італійському полотні. Полотна повністю закінчені, натягнуті на дерев\'яний підрамник, покриті подвійним шаром акрилового лаку для захисту від вигоряння фарби або механічних впливів на неї.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643908844/Filter/abstraction/itrm_0023-800x800_buw6si.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643908844/Filter/abstraction/itrm_0022-800x800_ukktip.jpg'],
        quantity: 1,
        name: "Модульні картини природи",
        currentPrice: 1505,
        categories: "modules",
        productUrl: "68",
        color: "red",
        size: "80x105",
        itemNo: "68",
        stars: 4,
        artist: 'Anna Smith',
        description: 'Модульні картини природи, написані маслом або художнім акрилом, професійними художниками вручну, з використанням декоративних матеріалів: структурних гелів та паст, акрилових контурів та медіумів. Усі модульні картини природи пишуться на натуральному італійському полотні. Полотна повністю закінчені, натягнуті на дерев\'яний підрамник, покриті подвійним шаром акрилового лаку для захисту від вигоряння фарби або механічних впливів на неї.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643909070/Filter/abstraction/itrm_0061-800x800_hmwpxt.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643909070/Filter/abstraction/itrm_0060-800x800_vpbjgs.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643909071/Filter/abstraction/itrm_0059-800x800_fhg689.jpg'],
        quantity: 1,
        name: "Модульні картини природи",
        currentPrice: 1505,
        categories: "modules",
        productUrl: "69",
        color: "black",
        size: "90x115",
        itemNo: "69",
        stars: 4,
        artist: 'Mark',
        description: 'Модульні картини природи, написані маслом або художнім акрилом, професійними художниками вручну, з використанням декоративних матеріалів: структурних гелів та паст, акрилових контурів та медіумів. Усі модульні картини природи пишуться на натуральному італійському полотні. Полотна повністю закінчені, натягнуті на дерев\'яний підрамник, покриті подвійним шаром акрилового лаку для захисту від вигоряння фарби або механічних впливів на неї.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643909211/Filter/abstraction/itrm_0064-800x800_khtg3g.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643909211/Filter/abstraction/itrm_0063-800x800_c7tamr.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643909211/Filter/abstraction/itrm_0062-800x800_ir6ghw.jpg'],
        quantity: 1,
        name: "Модульні картини природи",
        currentPrice: 1035,
        categories: "modules",
        productUrl: "70",
        color: "green",
        size: "100x130",
        itemNo: "70",
        stars: 4,
        artist: 'Maria',
        description: 'Модульні картини природи, написані маслом або художнім акрилом, професійними художниками вручну, з використанням декоративних матеріалів: структурних гелів та паст, акрилових контурів та медіумів. Усі модульні картини природи пишуться на натуральному італійському полотні. Полотна повністю закінчені, натягнуті на дерев\'яний підрамник, покриті подвійним шаром акрилового лаку для захисту від вигоряння фарби або механічних впливів на неї.',
    },
    {
        enabled: true,
        imageUrls: ['https://res.cloudinary.com/dhguqxbi6/image/upload/v1643909375/Filter/abstraction/itrm_0072-800x800_vfrt4c.jpg', 'https://res.cloudinary.com/dhguqxbi6/image/upload/v1643909375/Filter/abstraction/itrm_0071-800x800_zafnim.jpg'],
        quantity: 1,
        name: "Модульні картини природи",
        currentPrice: 1040,
        categories: "modules",
        productUrl: "71",
        color: "black",
        size: "60x80",
        itemNo: "71",
        stars: 4,
        artist: 'Roman',
        description: 'Модульні картини природи, написані маслом або художнім акрилом, професійними художниками вручну, з використанням декоративних матеріалів: структурних гелів та паст, акрилових контурів та медіумів. Усі модульні картини природи пишуться на натуральному італійському полотні. Полотна повністю закінчені, натягнуті на дерев\'яний підрамник, покриті подвійним шаром акрилового лаку для захисту від вигоряння фарби або механічних впливів на неї.',
    },
]